-- EverNight 扫描/字典数据（独立于 init.sql，便于维护）
-- 说明：本文件仅负责填充字典数据；建表请见 sql/init.sql

SET NAMES utf8mb4;
USE evernight;

INSERT IGNORE INTO dict_admin_path (path_value, enabled, rule_text, created_at, updated_at)
VALUES
  ('/admin', 1, '常见后台入口', NOW(), NOW()),
  ('/admin/', 1, '常见后台入口（目录形式）', NOW(), NOW()),
  ('/admin/login', 1, '常见后台登录入口', NOW(), NOW()),
  ('/administrator', 1, '常见后台入口（administrator）', NOW(), NOW()),
  ('/manage', 1, '常见后台入口（manage）', NOW(), NOW()),
  ('/manager', 1, '常见后台入口（manager）', NOW(), NOW()),
  ('/console', 1, '常见后台入口（console）', NOW(), NOW()),
  ('/wp-admin', 1, 'WordPress 后台入口', NOW(), NOW()),
  ('/phpmyadmin', 1, 'phpMyAdmin 管理入口', NOW(), NOW()),
  ('/druid/index.html', 1, 'Druid 监控/管理入口', NOW(), NOW())
;

INSERT IGNORE INTO dict_sensitive_path (path_value, enabled, rule_text, created_at, updated_at)
VALUES
  ('/.git/config', 1, '泄露 Git 仓库配置', NOW(), NOW()),
  ('/.env', 1, '泄露环境变量/密钥', NOW(), NOW()),
  ('/.svn/entries', 1, '泄露 SVN 元数据', NOW(), NOW()),
  ('/WEB-INF/web.xml', 1, '泄露 Java Web 配置（可能包含敏感信息）', NOW(), NOW()),
  ('/application.yml', 1, '泄露应用配置（YAML）', NOW(), NOW()),
  ('/application.properties', 1, '泄露应用配置（properties）', NOW(), NOW()),
  ('/v3/api-docs', 1, '暴露 OpenAPI 文档（v3）', NOW(), NOW()),
  ('/swagger-ui/index.html', 1, '暴露 Swagger UI 文档入口', NOW(), NOW()),
  ('/doc.html', 1, '暴露 Knife4j 文档入口', NOW(), NOW()),
  ('/actuator/env', 1, '暴露 Actuator 环境信息', NOW(), NOW())
;

INSERT IGNORE INTO dict_high_risk_port (port_spec, enabled, rule_text, created_at, updated_at)
VALUES
  ('21', 1, 'FTP 服务暴露（可能存在弱口令/匿名访问）', NOW(), NOW()),
  ('22', 1, 'SSH 服务暴露', NOW(), NOW()),
  ('23', 1, 'Telnet 服务暴露（明文协议）', NOW(), NOW()),
  ('25', 1, 'SMTP 服务暴露（可能被滥用）', NOW(), NOW()),
  ('53', 1, 'DNS 服务暴露（需关注递归/传送配置）', NOW(), NOW()),
  ('135', 1, 'RPC 服务暴露（Windows）', NOW(), NOW()),
  ('139', 1, 'NetBIOS 服务暴露（Windows）', NOW(), NOW()),
  ('161', 1, 'SNMP 服务暴露（可能存在默认团体字）', NOW(), NOW()),
  ('389', 1, 'LDAP 服务暴露（可能存在匿名绑定/信息泄露）', NOW(), NOW()),
  ('445', 1, 'SMB 服务暴露（Windows）', NOW(), NOW()),
  ('1433', 1, 'MSSQL 服务暴露', NOW(), NOW()),
  ('1521', 1, 'Oracle 服务暴露', NOW(), NOW()),
  ('2181', 1, 'ZooKeeper 服务暴露（可能未鉴权）', NOW(), NOW()),
  ('2375', 1, 'Docker API 暴露（高危：可能未鉴权）', NOW(), NOW()),
  ('2379', 1, 'etcd 服务暴露（可能未鉴权）', NOW(), NOW()),
  ('3306', 1, 'MySQL 服务暴露', NOW(), NOW()),
  ('3389', 1, 'RDP 服务暴露（Windows）', NOW(), NOW()),
  ('5432', 1, 'PostgreSQL 服务暴露', NOW(), NOW()),
  ('5900', 1, 'VNC 服务暴露（可能无加密/弱口令）', NOW(), NOW()),
  ('6379', 1, 'Redis 服务暴露（可能未鉴权）', NOW(), NOW()),
  ('9200', 1, 'Elasticsearch 服务暴露（可能未鉴权）', NOW(), NOW()),
  ('9300', 1, 'Elasticsearch 集群通信端口暴露', NOW(), NOW()),
  ('11211', 1, 'Memcached 服务暴露（可能未鉴权）', NOW(), NOW()),
  ('27017', 1, 'MongoDB 服务暴露（可能未鉴权）', NOW(), NOW()),
  ('5601', 1, 'Kibana 控制台暴露', NOW(), NOW()),
  ('10000', 1, 'Webmin 控制台暴露', NOW(), NOW())
;

INSERT IGNORE INTO dict_common_port (port_spec)
VALUES
  ('1-7'),
  ('9'),
  ('13'),
  ('17'),
  ('19'),
  ('20-23'),
  ('25'),
  ('37'),
  ('42'),
  ('43'),
  ('49'),
  ('53'),
  ('70'),
  ('79-82'),
  ('88'),
  ('102'),
  ('110'),
  ('111'),
  ('113'),
  ('119'),
  ('123'),
  ('135'),
  ('139'),
  ('143'),
  ('161-162'),
  ('179'),
  ('199'),
  ('211'),
  ('212'),
  ('222'),
  ('254-255'),
  ('256'),
  ('259'),
  ('264'),
  ('280'),
  ('301'),
  ('306'),
  ('311'),
  ('340'),
  ('366'),
  ('389'),
  ('406'),
  ('407'),
  ('416-417'),
  ('425'),
  ('427'),
  ('443'),
  ('444'),
  ('445'),
  ('458'),
  ('464'),
  ('465'),
  ('481'),
  ('497'),
  ('500'),
  ('512-515'),
  ('524'),
  ('541'),
  ('543-544'),
  ('548'),
  ('554'),
  ('555'),
  ('563'),
  ('587'),
  ('593'),
  ('616'),
  ('617'),
  ('625'),
  ('631'),
  ('636'),
  ('646'),
  ('648'),
  ('666-668'),
  ('683'),
  ('687'),
  ('691'),
  ('700'),
  ('705'),
  ('711'),
  ('714'),
  ('720'),
  ('722'),
  ('726'),
  ('749'),
  ('765'),
  ('777'),
  ('783'),
  ('787'),
  ('800'),
  ('801'),
  ('808'),
  ('843'),
  ('873'),
  ('880'),
  ('888'),
  ('898'),
  ('900'),
  ('901'),
  ('902'),
  ('903'),
  ('911'),
  ('912'),
  ('981'),
  ('987'),
  ('990'),
  ('992'),
  ('993'),
  ('995'),
  ('999'),
  ('1000'),
  ('1001'),
  ('1002'),
  ('1007'),
  ('1009'),
  ('1010'),
  ('1011'),
  ('1021'),
  ('1022'),
  ('1023'),
  ('1024-1033'),
  ('1035'),
  ('1036'),
  ('1038'),
  ('1040'),
  ('1041'),
  ('1044'),
  ('1048'),
  ('1050'),
  ('1053'),
  ('1054'),
  ('1056'),
  ('1058'),
  ('1059'),
  ('1064-1066'),
  ('1069'),
  ('1071'),
  ('1074'),
  ('1080'),
  ('1083'),
  ('1085'),
  ('1099'),
  ('1100'),
  ('1102'),
  ('1104'),
  ('1105'),
  ('1106'),
  ('1110'),
  ('1111'),
  ('1112'),
  ('1114'),
  ('1117'),
  ('1119'),
  ('1121'),
  ('1122'),
  ('1123'),
  ('1124'),
  ('1126'),
  ('1130'),
  ('1131'),
  ('1132'),
  ('1137'),
  ('1138'),
  ('1141'),
  ('1145'),
  ('1147'),
  ('1148'),
  ('1151'),
  ('1152'),
  ('1154'),
  ('1163'),
  ('1164'),
  ('1165'),
  ('1166'),
  ('1174'),
  ('1175'),
  ('1183'),
  ('1185'),
  ('1186'),
  ('1187'),
  ('1192'),
  ('1198'),
  ('1199'),
  ('1201'),
  ('1213'),
  ('1216'),
  ('1217'),
  ('1218'),
  ('1233'),
  ('1234'),
  ('1236'),
  ('1244'),
  ('1247'),
  ('1248'),
  ('1259'),
  ('1271'),
  ('1272'),
  ('1277'),
  ('1287'),
  ('1296'),
  ('1300')
;

INSERT IGNORE INTO dict_common_port (port_spec)
VALUES
  ('1301'),
  ('1309'),
  ('1310'),
  ('1311'),
  ('1322'),
  ('1328'),
  ('1334'),
  ('1352'),
  ('1417'),
  ('1433'),
  ('1434'),
  ('1443'),
  ('1455'),
  ('1461'),
  ('1494'),
  ('1500'),
  ('1501'),
  ('1503'),
  ('1521'),
  ('1524'),
  ('1533'),
  ('1556'),
  ('1580'),
  ('1583'),
  ('1594'),
  ('1600'),
  ('1641'),
  ('1658'),
  ('1666'),
  ('1687'),
  ('1688'),
  ('1700'),
  ('1717'),
  ('1718'),
  ('1719'),
  ('1720'),
  ('1723'),
  ('1755'),
  ('1761'),
  ('1782'),
  ('1783'),
  ('1801'),
  ('1805'),
  ('1812'),
  ('1839'),
  ('1840'),
  ('1862'),
  ('1863'),
  ('1864'),
  ('1875'),
  ('1900'),
  ('1914'),
  ('1935'),
  ('1947'),
  ('1971'),
  ('1972'),
  ('1974'),
  ('1984'),
  ('1998'),
  ('1999'),
  ('2000-2005'),
  ('2010'),
  ('2020'),
  ('2021'),
  ('2022'),
  ('2030'),
  ('2033'),
  ('2034'),
  ('2035'),
  ('2038'),
  ('2040'),
  ('2041'),
  ('2042'),
  ('2043'),
  ('2045'),
  ('2046'),
  ('2047'),
  ('2048'),
  ('2050'),
  ('2065'),
  ('2068'),
  ('2082'),
  ('2083'),
  ('2086'),
  ('2087'),
  ('2095'),
  ('2096'),
  ('2100'),
  ('2103'),
  ('2105'),
  ('2106'),
  ('2111'),
  ('2119'),
  ('2121'),
  ('2126'),
  ('2135'),
  ('2144'),
  ('2160'),
  ('2161'),
  ('2170'),
  ('2179'),
  ('2181'),
  ('2190'),
  ('2191'),
  ('2196'),
  ('2200'),
  ('2222'),
  ('2251'),
  ('2260'),
  ('2288'),
  ('2301'),
  ('2323'),
  ('2366'),
  ('2381'),
  ('2382'),
  ('2383'),
  ('2393'),
  ('2394'),
  ('2399'),
  ('2401'),
  ('2492'),
  ('2500'),
  ('2522'),
  ('2525'),
  ('2557'),
  ('2601'),
  ('2602'),
  ('2604'),
  ('2605'),
  ('2607'),
  ('2608'),
  ('2638'),
  ('2701'),
  ('2702'),
  ('2710'),
  ('2717'),
  ('2718'),
  ('2725'),
  ('2800'),
  ('2809'),
  ('2811'),
  ('2869'),
  ('2875'),
  ('2909'),
  ('2910'),
  ('2920'),
  ('2967'),
  ('2968'),
  ('2998'),
  ('3000-3007'),
  ('3011'),
  ('3013'),
  ('3017'),
  ('3030'),
  ('3031'),
  ('3052'),
  ('3071'),
  ('3077'),
  ('3128'),
  ('3168'),
  ('3211'),
  ('3221'),
  ('3260'),
  ('3261'),
  ('3268'),
  ('3269'),
  ('3283'),
  ('3300'),
  ('3306'),
  ('3333'),
  ('3389'),
  ('3390'),
  ('3404'),
  ('3476'),
  ('3493'),
  ('3517'),
  ('3527'),
  ('3546'),
  ('3551'),
  ('3580'),
  ('3659'),
  ('3689'),
  ('3690'),
  ('3703'),
  ('3737'),
  ('3766'),
  ('3784'),
  ('3800'),
  ('3801'),
  ('3809'),
  ('3814'),
  ('3826'),
  ('3827'),
  ('3828'),
  ('3851'),
  ('3869'),
  ('3871'),
  ('3878'),
  ('3880'),
  ('3889')
;

INSERT IGNORE INTO dict_common_port (port_spec)
VALUES
  ('3905'),
  ('3914'),
  ('3918'),
  ('3920'),
  ('3945'),
  ('3971'),
  ('3986'),
  ('3995'),
  ('3998'),
  ('4000'),
  ('4001'),
  ('4002'),
  ('4003'),
  ('4004'),
  ('4005'),
  ('4045'),
  ('4111'),
  ('4125'),
  ('4126'),
  ('4141'),
  ('4155'),
  ('4190'),
  ('4224'),
  ('4242'),
  ('4279'),
  ('4321'),
  ('4343'),
  ('4443'),
  ('4444'),
  ('4445'),
  ('4455'),
  ('4500'),
  ('4567'),
  ('4662'),
  ('4848'),
  ('4899'),
  ('4900'),
  ('4998'),
  ('5000'),
  ('5001'),
  ('5002'),
  ('5003'),
  ('5009'),
  ('5030'),
  ('5033'),
  ('5050'),
  ('5051'),
  ('5060'),
  ('5061'),
  ('5080'),
  ('5090'),
  ('5100'),
  ('5101'),
  ('5120'),
  ('5190'),
  ('5200'),
  ('5214'),
  ('5221'),
  ('5222'),
  ('5225'),
  ('5226'),
  ('5269'),
  ('5280'),
  ('5298'),
  ('5357'),
  ('5405'),
  ('5414'),
  ('5432'),
  ('5500'),
  ('5510'),
  ('5544'),
  ('5555'),
  ('5560'),
  ('5631'),
  ('5666'),
  ('5672'),
  ('5678'),
  ('5683'),
  ('5718'),
  ('5730'),
  ('5800'),
  ('5801'),
  ('5802'),
  ('5810'),
  ('5811'),
  ('5815'),
  ('5822'),
  ('5825'),
  ('5850'),
  ('5859'),
  ('5862'),
  ('5877'),
  ('5900-5904'),
  ('5906'),
  ('5907'),
  ('5910'),
  ('5911'),
  ('5915'),
  ('5922'),
  ('5925'),
  ('5950'),
  ('5952'),
  ('5960'),
  ('5987'),
  ('5988'),
  ('5989'),
  ('5998'),
  ('5999'),
  ('6000-6007'),
  ('6009'),
  ('6025'),
  ('6059'),
  ('6101'),
  ('6106'),
  ('6112'),
  ('6123'),
  ('6129'),
  ('6156'),
  ('6346'),
  ('6389'),
  ('6502'),
  ('6510'),
  ('6543'),
  ('6547'),
  ('6565'),
  ('6566'),
  ('6567'),
  ('6580'),
  ('6646'),
  ('6666'),
  ('6667'),
  ('6668'),
  ('6669'),
  ('6689'),
  ('6692'),
  ('6699'),
  ('6779'),
  ('6788'),
  ('6789'),
  ('6792'),
  ('6839'),
  ('6881'),
  ('6901'),
  ('6969'),
  ('7000-7002'),
  ('7004'),
  ('7007'),
  ('7019'),
  ('7025'),
  ('7070'),
  ('7100'),
  ('7106'),
  ('7200'),
  ('7201'),
  ('7402'),
  ('7435'),
  ('7443'),
  ('7496'),
  ('7512'),
  ('7547'),
  ('7548'),
  ('7625'),
  ('7627'),
  ('7676'),
  ('7741'),
  ('7777'),
  ('7778'),
  ('7800'),
  ('7911'),
  ('7920'),
  ('7921'),
  ('7937'),
  ('7999'),
  ('8000-8010'),
  ('8021'),
  ('8022'),
  ('8031'),
  ('8042'),
  ('8045'),
  ('8080-8082'),
  ('8086'),
  ('8087'),
  ('8090'),
  ('8093'),
  ('8099'),
  ('8100'),
  ('8180'),
  ('8181'),
  ('8192'),
  ('8200'),
  ('8222'),
  ('8254'),
  ('8290'),
  ('8291'),
  ('8333'),
  ('8383'),
  ('8400'),
  ('8402'),
  ('8443'),
  ('8500')
;

INSERT IGNORE INTO dict_common_port (port_spec)
VALUES
  ('8600'),
  ('8649'),
  ('8651'),
  ('8652'),
  ('8654'),
  ('8701'),
  ('8800'),
  ('8873'),
  ('8888'),
  ('8899'),
  ('8994'),
  ('9000-9003'),
  ('9009'),
  ('9010'),
  ('9040'),
  ('9050'),
  ('9071'),
  ('9080'),
  ('9081'),
  ('9090'),
  ('9091'),
  ('9099'),
  ('9100'),
  ('9102'),
  ('9110'),
  ('9111'),
  ('9200'),
  ('9207'),
  ('9220'),
  ('9290'),
  ('9415'),
  ('9418'),
  ('9485'),
  ('9500'),
  ('9502'),
  ('9503'),
  ('9535'),
  ('9575'),
  ('9593'),
  ('9594'),
  ('9595'),
  ('9618'),
  ('9666'),
  ('9876'),
  ('9877'),
  ('9878'),
  ('9898'),
  ('9900'),
  ('9917'),
  ('9929'),
  ('9943'),
  ('9998'),
  ('9999'),
  ('10000'),
  ('10001'),
  ('10002'),
  ('10003'),
  ('10004'),
  ('10009'),
  ('10010'),
  ('10012'),
  ('10024'),
  ('10025'),
  ('10082'),
  ('10180'),
  ('10215'),
  ('10243'),
  ('10566'),
  ('10616'),
  ('10617'),
  ('10621'),
  ('10626'),
  ('10628'),
  ('10629'),
  ('10778'),
  ('11110'),
  ('11111'),
  ('11967'),
  ('12000'),
  ('12174'),
  ('12265'),
  ('12345'),
  ('13456'),
  ('13722'),
  ('13782'),
  ('13783'),
  ('14000'),
  ('14238'),
  ('14441'),
  ('15000'),
  ('15002'),
  ('15003'),
  ('15004'),
  ('15660'),
  ('15742'),
  ('16000'),
  ('16001'),
  ('16012'),
  ('16016'),
  ('16018'),
  ('16080'),
  ('16113'),
  ('16992'),
  ('16993'),
  ('17877'),
  ('17988'),
  ('18040'),
  ('18101'),
  ('18988'),
  ('19101'),
  ('19283'),
  ('19315'),
  ('19350'),
  ('19780'),
  ('19801'),
  ('19842'),
  ('20000'),
  ('20005'),
  ('20031'),
  ('20221'),
  ('20222'),
  ('20828'),
  ('21571'),
  ('22939'),
  ('23502'),
  ('24444'),
  ('24800'),
  ('25734'),
  ('25735'),
  ('26214'),
  ('27000'),
  ('27352'),
  ('27353'),
  ('27355'),
  ('27356'),
  ('27715'),
  ('28201'),
  ('30000'),
  ('30718'),
  ('30951'),
  ('31038'),
  ('31337'),
  ('32768-32785'),
  ('33354'),
  ('33899'),
  ('34571'),
  ('34572'),
  ('34573'),
  ('35500'),
  ('38292'),
  ('40193'),
  ('40911'),
  ('41511'),
  ('42510'),
  ('44176'),
  ('44442'),
  ('44443'),
  ('44501'),
  ('45100'),
  ('48080'),
  ('49152-49157'),
  ('50000'),
  ('50001'),
  ('50002'),
  ('50003'),
  ('50006'),
  ('50300'),
  ('50389'),
  ('50500'),
  ('50636'),
  ('50800'),
  ('51103'),
  ('51493'),
  ('52673'),
  ('52822'),
  ('52848'),
  ('52869'),
  ('54045'),
  ('54328'),
  ('55055'),
  ('55056'),
  ('55555'),
  ('55600'),
  ('56737'),
  ('56738'),
  ('57294'),
  ('57797'),
  ('58080'),
  ('60020'),
  ('60443'),
  ('61532'),
  ('61900'),
  ('62078'),
  ('63331'),
  ('64623'),
  ('64680'),
  ('65000'),
  ('65129'),
  ('65389'),
  ('65535')
;

INSERT IGNORE INTO dict_subdomain (subdomain)
VALUES
  ('www'),
  ('api'),
  ('admin'),
  ('test'),
  ('dev'),
  ('staging'),
  ('uat'),
  ('prod'),
  ('beta'),
  ('alpha'),
  ('m'),
  ('mobile'),
  ('wap'),
  ('app'),
  ('static'),
  ('img'),
  ('images'),
  ('cdn'),
  ('assets'),
  ('file'),
  ('files'),
  ('download'),
  ('downloads'),
  ('upload'),
  ('uploads'),
  ('docs'),
  ('doc'),
  ('wiki'),
  ('blog'),
  ('status'),
  ('monitor'),
  ('metrics'),
  ('grafana'),
  ('kibana'),
  ('elk'),
  ('log'),
  ('logs'),
  ('mail'),
  ('smtp'),
  ('imap'),
  ('pop'),
  ('pop3'),
  ('webmail'),
  ('mx'),
  ('ns1'),
  ('ns2'),
  ('dns'),
  ('ftp'),
  ('sftp'),
  ('ssh'),
  ('vpn'),
  ('portal'),
  ('intranet'),
  ('internal'),
  ('oa'),
  ('hr'),
  ('finance'),
  ('pay'),
  ('payment'),
  ('billing'),
  ('account'),
  ('accounts'),
  ('auth'),
  ('sso'),
  ('login'),
  ('register'),
  ('signup'),
  ('user'),
  ('users'),
  ('member'),
  ('members'),
  ('crm'),
  ('erp'),
  ('cms'),
  ('shop'),
  ('store'),
  ('cart'),
  ('order'),
  ('orders'),
  ('search'),
  ('query'),
  ('data'),
  ('db'),
  ('mysql'),
  ('postgres'),
  ('redis'),
  ('mq'),
  ('rabbitmq'),
  ('kafka'),
  ('zk'),
  ('consul'),
  ('etcd'),
  ('git'),
  ('gitlab'),
  ('gitea'),
  ('svn'),
  ('jira'),
  ('help'),
  ('support'),
  ('ticket')
;


INSERT IGNORE INTO dict_cdn_fingerprint (fingerprint_value, enabled, rule_text, created_at, updated_at)
VALUES
  ('15cdn.com', 1, '腾正安全加速(原 15CDN)', NOW(), NOW()),
  ('tzcdn.cn', 1, '腾正安全加速(原 15CDN)', NOW(), NOW()),
  ('cedexis.net', 1, 'Cedexis GSLB', NOW(), NOW()),
  ('cdxcn.cn', 1, 'Cedexis GSLB (For China)', NOW(), NOW()),
  ('qhcdn.com', 1, '360 云 CDN (由奇安信运营)', NOW(), NOW()),
  ('qh-cdn.com', 1, '360 云 CDN (由奇虎 360 运营)', NOW(), NOW()),
  ('qihucdn.com', 1, '360 云 CDN (由奇虎 360 运营)', NOW(), NOW()),
  ('360cdn.com', 1, '360 云 CDN (由奇虎 360 运营)', NOW(), NOW()),
  ('360cloudwaf.com', 1, '奇安信网站卫士', NOW(), NOW()),
  ('360anyu.com', 1, '奇安信网站卫士', NOW(), NOW()),
  ('360safedns.com', 1, '奇安信网站卫士', NOW(), NOW()),
  ('360wzws.com', 1, '奇安信网站卫士', NOW(), NOW()),
  ('qaxwzws.com', 1, '奇安信网站卫士', NOW(), NOW()),
  ('qaxcloudwaf.com', 1, '奇安信网神防火墙', NOW(), NOW()),
  ('akamai.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('akamaiedge.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('ytcdn.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('edgesuite.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('akamaitech.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('akamaitechnologies.com', 1, 'Akamai CDN', NOW(), NOW()),
  ('edgekey.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('akam.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('akagtm.org', 1, 'Akamai CDN', NOW(), NOW()),
  ('akamaistream.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('tl88.net', 1, '易通锐进(Akamai 中国)由网宿承接', NOW(), NOW()),
  ('cloudfront.net', 1, 'AWS CloudFront', NOW(), NOW()),
  ('worldcdn.net', 1, 'CDN.NET', NOW(), NOW()),
  ('worldssl.net', 1, 'CDN.NET / CDNSUN / ONAPP', NOW(), NOW()),
  ('cdn77.org', 1, 'CDN77', NOW(), NOW()),
  ('panthercdn.com', 1, 'CDNetworks', NOW(), NOW()),
  ('cdnga.net', 1, 'CDNetworks', NOW(), NOW()),
  ('cdngc.net', 1, 'CDNetworks', NOW(), NOW()),
  ('gccdn.net', 1, 'CDNetworks', NOW(), NOW()),
  ('gccdn.cn', 1, 'CDNetworks', NOW(), NOW()),
  ('akamaized.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('126.net', 1, '网易云 CDN', NOW(), NOW()),
  ('127.net', 1, '网易云 CDN', NOW(), NOW()),
  ('lf127.net', 1, '网易云 CDN', NOW(), NOW()),
  ('163jiasu.com', 1, '网易云 CDN', NOW(), NOW()),
  ('easebar.com', 1, '网易云 CDN', NOW(), NOW()),
  ('nease.net', 1, '网易云 CDN', NOW(), NOW()),
  ('amazonaws.com', 1, 'AWS Cloud', NOW(), NOW()),
  ('cdn77.net', 1, 'CDN77', NOW(), NOW()),
  ('cdnify.io', 1, 'CDNIFY', NOW(), NOW()),
  ('cdnsun.net', 1, 'CDNSUN', NOW(), NOW()),
  ('bdydns.com', 1, '百度云 CDN', NOW(), NOW()),
  ('jomodns.com', 1, '百度云 CDN', NOW(), NOW()),
  ('baidupcs.com', 1, '百度网盘', NOW(), NOW()),
  ('ccgslb.com.cn', 1, '蓝汛 CDN', NOW(), NOW()),
  ('ccgslb.net', 1, '蓝汛 CDN', NOW(), NOW()),
  ('ccgslb.com', 1, '蓝汛 CDN', NOW(), NOW()),
  ('ccgslb.cn', 1, '蓝汛 CDN', NOW(), NOW()),
  ('c3cache.net', 1, '蓝汛 CDN', NOW(), NOW()),
  ('c3dns.net', 1, '蓝汛 CDN', NOW(), NOW()),
  ('chinacache.net', 1, '蓝汛 CDN', NOW(), NOW()),
  ('wswebcdn.com', 1, '网宿 CDN', NOW(), NOW()),
  ('lxdns.com', 1, '网宿 CDN', NOW(), NOW()),
  ('8686c.com', 1, '网宿 CDN', NOW(), NOW()),
  ('wswebpic.com', 1, '网宿 CDN', NOW(), NOW()),
  ('qtlglb.com', 1, '网宿海外 CDN', NOW(), NOW()),
  ('cloudflare.net', 1, 'Cloudflare', NOW(), NOW()),
  ('cloudflare.com', 1, 'Cloudflare', NOW(), NOW()),
  ('cloudflarestorage.com', 1, 'Cloudflare对象储存', NOW(), NOW()),
  ('cf-ns.net', 1, 'Cloudflare中国', NOW(), NOW()),
  ('workers.dev', 1, 'Cloudflare Workers', NOW(), NOW()),
  ('pages.dev', 1, 'Cloudflare Pages', NOW(), NOW()),
  ('vercel.app', 1, 'Vercel', NOW(), NOW()),
  ('ppio.cloud', 1, 'PPIO边缘PCDN节点', NOW(), NOW()),
  ('akadns.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('akamaihd.net', 1, 'Akamai CDN', NOW(), NOW()),
  ('chinanetcenter.com', 1, '网宿 CDN', NOW(), NOW()),
  ('customcdn.com.cn', 1, '网宿 CDN', NOW(), NOW()),
  ('customcdn.cn', 1, '网宿 CDN', NOW(), NOW()),
  ('51cdn.com', 1, '网宿 CDN', NOW(), NOW()),
  ('wscdns.com', 1, '网宿 CDN', NOW(), NOW()),
  ('cdn20.com', 1, '网宿 CDN', NOW(), NOW()),
  ('wsdvs.com', 1, '网宿 CDN', NOW(), NOW()),
  ('wsglb0.com', 1, '网宿 CDN', NOW(), NOW()),
  ('speedcdns.com', 1, '网宿 CDN', NOW(), NOW()),
  ('wtxcdn.com', 1, '网宿 CDN', NOW(), NOW()),
  ('wsssec.com', 1, '网宿 WAF CDN', NOW(), NOW()),
  ('wcdnga.com', 1, '网宿 WAF CDN', NOW(), NOW()),
  ('fastly.net', 1, 'Fastly', NOW(), NOW()),
  ('fastlylb.net', 1, 'Fastly', NOW(), NOW()),
  ('hwcdn.net', 1, 'Stackpath (原 Highwinds)', NOW(), NOW()),
  ('incapdns.net', 1, 'Incapsula CDN', NOW(), NOW()),
  ('kxcdn.com', 1, 'KeyCDN', NOW(), NOW()),
  ('lswcdn.net', 1, 'LeaseWeb CDN', NOW(), NOW()),
  ('mwcloudcdn.com', 1, 'QUANTIL (网宿)', NOW(), NOW()),
  ('mwcname.com', 1, 'QUANTIL (网宿)', NOW(), NOW()),
  ('azureedge.net', 1, 'Microsoft Azure CDN', NOW(), NOW()),
  ('msecnd.net', 1, 'Microsoft Azure CDN', NOW(), NOW()),
  ('mschcdn.com', 1, 'Microsoft Azure CDN', NOW(), NOW()),
  ('v0cdn.net', 1, 'Microsoft Azure CDN', NOW(), NOW()),
  ('azurewebsites.net', 1, 'Microsoft Azure App Service', NOW(), NOW()),
  ('azurewebsites.windows.net', 1, 'Microsoft Azure App Service', NOW(), NOW()),
  ('trafficmanager.net', 1, 'Microsoft Azure Traffic Manager', NOW(), NOW()),
  ('cloudapp.net', 1, 'Microsoft Azure', NOW(), NOW()),
  ('chinacloudsites.cn', 1, '世纪互联旗下上海蓝云(承载 Azure 中国)', NOW(), NOW()),
  ('chinacloudapi.cn', 1, '世纪互联旗下上海蓝云(承载 Azure 中国)', NOW(), NOW()),
  ('spdydns.com', 1, '云端智度融合 CDN', NOW(), NOW()),
  ('jiashule.com', 1, '知道创宇云安全加速乐CDN', NOW(), NOW()),
  ('jiasule.org', 1, '知道创宇云安全加速乐CDN', NOW(), NOW()),
  ('365cyd.cn', 1, '知道创宇云安全创宇盾(政务专用)', NOW(), NOW()),
  ('myhuaweicloud.com', 1, '华为云 对象储存', NOW(), NOW()),
  ('huaweicloud.com', 1, '华为云WAF高防云盾', NOW(), NOW()),
  ('myhwcdn.cn', 1, '华为云 CDN', NOW(), NOW()),
  ('cdnhwc1.com', 1, '华为云 CDN', NOW(), NOW()),
  ('cdnhwc2.com', 1, '华为云 CDN', NOW(), NOW()),
  ('cdnhwc3.com', 1, '华为云 CDN', NOW(), NOW()),
  ('cdnhwcprh113.com', 1, '华为云 CDN', NOW(), NOW()),
  ('cdn36.com', 1, '商中在线', NOW(), NOW()),
  ('dnion.com', 1, '帝联科技', NOW(), NOW()),
  ('ewcache.com', 1, '帝联科技', NOW(), NOW()),
  ('globalcdn.cn', 1, '帝联科技', NOW(), NOW()),
  ('tlgslb.com', 1, '帝联科技', NOW(), NOW()),
  ('fastcdn.com', 1, '帝联科技', NOW(), NOW()),
  ('flxdns.com', 1, '帝联科技', NOW(), NOW()),
  ('dlgslb.cn', 1, '帝联科技', NOW(), NOW()),
  ('newdefend.cn', 1, '牛盾云安全', NOW(), NOW()),
  ('ffdns.net', 1, 'CloudXNS', NOW(), NOW()),
  ('aocdn.com', 1, '可靠云 CDN (贴图库)', NOW(), NOW()),
  ('baishancdnx.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('baishancdnx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('baishancdnx.net', 1, '白山云 CDN', NOW(), NOW()),
  ('baishancdnx.top', 1, '白山云 CDN', NOW(), NOW()),
  ('aishandnsx.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('baishandnsx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('baishandnsx.net', 1, '白山云 CDN', NOW(), NOW()),
  ('baishandnsx.top', 1, '白山云 CDN', NOW(), NOW()),
  ('baishangeek.com', 1, '白山云 CDN', NOW(), NOW()),
  ('baishangeek.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('bscstorage.net', 1, '白山云 CDN', NOW(), NOW()),
  ('bscstorage.com', 1, '白山云 CDN', NOW(), NOW()),
  ('bscstorage.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('bsgslb.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('bsgslb.com', 1, '白山云 CDN', NOW(), NOW()),
  ('qingcdn.com', 1, '白山云 CDN', NOW(), NOW()),
  ('bsclink.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('bsclink.com', 1, '白山云 CDN', NOW(), NOW()),
  ('trpcdn.com', 1, '白山云 CDN', NOW(), NOW()),
  ('trpcdn.net', 1, '白山云 CDN', NOW(), NOW()),
  ('bsccdn.net', 1, '白山云 CDN', NOW(), NOW()),
  ('bsccdn.com', 1, '白山云 CDN', NOW(), NOW()),
  ('eccdnx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('crazyrtc.com', 1, '白山云 CDN', NOW(), NOW()),
  ('baishan-cloud.com', 1, '白山云 CDN', NOW(), NOW()),
  ('baishan-cloud.net', 1, '白山云 CDN', NOW(), NOW()),
  ('baicdnx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('scdncloud.com', 1, '白山云 CDN', NOW(), NOW()),
  ('scdntop.com', 1, '白山云 CDN', NOW(), NOW()),
  ('zzcdnx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfincdnx.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfincdnx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfincdnx.net', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfincdnx.top', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfindnsx.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfindnsx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfindnsx.net', 1, '白山云 CDN', NOW(), NOW()),
  ('dolfindnsx.top', 1, '白山云 CDN', NOW(), NOW()),
  ('saxyit.com', 1, '白山云鲁班 PCDN', NOW(), NOW()),
  ('bsydns.com', 1, '白山云 CDN', NOW(), NOW()),
  ('bsydns.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('bsydns.net', 1, '白山云 CDN', NOW(), NOW()),
  ('5gcdnx.com', 1, '白山云 CDN', NOW(), NOW()),
  ('bscdns.com', 1, '白山云 CDN', NOW(), NOW()),
  ('bscedge.com', 1, '白山云 CDN', NOW(), NOW()),
  ('baishan-gateway.com', 1, '白山云 CDN', NOW(), NOW()),
  ('edgefn.net', 1, '白山云 CDN', NOW(), NOW()),
  ('fnedge.net', 1, '白山云 CDN', NOW(), NOW()),
  ('ldgslb.com', 1, '白山云 CDN', NOW(), NOW()),
  ('bscgslb.com', 1, '白山云 CDN', NOW(), NOW()),
  ('ccedge.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('whitecdnx.cn', 1, '白山云 CDN', NOW(), NOW()),
  ('baishancloud.net', 1, '白山云 CDN', NOW(), NOW()),
  ('revivalark.com', 1, '白山云 CDN', NOW(), NOW()),
  ('wanwang.space', 1, '白山云 CDN', NOW(), NOW()),
  ('anquan.io', 1, '牛盾云安全', NOW(), NOW()),
  ('cloudglb.com', 1, '快网 CDN', NOW(), NOW()),
  ('fastweb.com', 1, '快网 CDN', NOW(), NOW()),
  ('fastwebcdn.com', 1, '快网 CDN', NOW(), NOW()),
  ('cloudcdn.net', 1, '快网 CDN', NOW(), NOW()),
  ('fwcdn.com', 1, '快网 CDN', NOW(), NOW()),
  ('fwdns.net', 1, '快网 CDN', NOW(), NOW()),
  ('hadns.net', 1, '快网 CDN', NOW(), NOW()),
  ('hacdn.net', 1, '快网 CDN', NOW(), NOW()),
  ('cachecn.com', 1, '快网 CDN', NOW(), NOW()),
  ('qingcache.com', 1, '青云 CDN', NOW(), NOW()),
  ('qingcloud.com', 1, '青云 CDN', NOW(), NOW()),
  ('frontwize.com', 1, '青云 CDN', NOW(), NOW()),
  ('msscdn.com', 1, '美团云 CDN', NOW(), NOW()),
  ('800cdn.com', 1, '西部数码', NOW(), NOW()),
  ('aliapp.com', 1, '阿里云', NOW(), NOW()),
  ('alivecdn.com', 1, '阿里云直播', NOW(), NOW()),
  ('tbcache.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('edu-aliyun.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alyns.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('alysm.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyunga.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyunedu.net', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyuncdn.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyuncdn.net', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliiotapp.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyunnest.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyunvcs.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyunrtc.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliappcdn.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliplus.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alirtc.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alisoft.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('alisoft.com.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('alisoft.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alibabacloudsso.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyuncds.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('kunlundns.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('h5video.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('scdncxtn.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('sfdcfd.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyunvpc.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('danuoyidns.net', 1, '阿里云 CDN', NOW(), NOW()),
  ('danuoyidns.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('cloudsecsase.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('scdndns.net', 1, '阿里云 CDN', NOW(), NOW()),
  ('scdndns.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('myalicdn.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('myalicdn.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('ialicdn.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyun-inc.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyuncs.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alikunlun.net', 1, '阿里云 CDN', NOW(), NOW()),
  ('alikunlun.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alicdn.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alicdn.net', 1, '阿里云 CDN', NOW(), NOW()),
  ('aliyun.com', 1, '阿里云 原生 常见于企业邮箱', NOW(), NOW()),
  ('alibabadns.com', 1, '阿里云 原生 常见于企业邮箱', NOW(), NOW()),
  ('aliyunddos1011.com', 1, '阿里云 DDOS', NOW(), NOW()),
  ('yundunwaf1.com', 1, '阿里云 WAF', NOW(), NOW()),
  ('yundunwaf2.com', 1, '阿里云 WAF', NOW(), NOW()),
  ('yundunwaf3.com', 1, '阿里云 WAF', NOW(), NOW()),
  ('yundunwaf4.com', 1, '阿里云 WAF', NOW(), NOW()),
  ('yundunwaf5.com', 1, '阿里云 WAF', NOW(), NOW()),
  ('mxhichina.com', 1, '阿里云 企业邮箱', NOW(), NOW()),
  ('aligaofang.com', 1, '阿里云盾高防', NOW(), NOW()),
  ('yundunddos.com', 1, '阿里云盾高防', NOW(), NOW()),
  ('queniucdn.com.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('queniugslb.com.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('edgegslb.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('cdngslb.com', 1, '阿里云 CDN', NOW(), NOW()),
  ('alidns.net', 1, '阿里云 DNS', NOW(), NOW()),
  ('alidns.com', 1, '阿里云 DNS', NOW(), NOW()),
  ('alidns.cn', 1, '阿里云 DNS', NOW(), NOW()),
  ('queniujq.cn', 1, '阿里云 CDN', NOW(), NOW()),
  ('yunjiasu-cdn.net', 1, '百度云加速', NOW(), NOW()),
  ('momentcdn.com', 1, '魔门云 CDN', NOW(), NOW()),
  ('aicdn.com', 1, '又拍云', NOW(), NOW()),
  ('qbox.me', 1, '七牛云', NOW(), NOW()),
  ('qiniu.com', 1, '七牛云', NOW(), NOW()),
  ('qiniudns.com', 1, '七牛云', NOW(), NOW()),
  ('qiniupic.com', 1, '七牛云', NOW(), NOW()),
  ('clouddn.com', 1, '七牛云', NOW(), NOW()),
  ('qiniucdn.com', 1, '七牛云', NOW(), NOW()),
  ('qiniudn.com', 1, '七牛云', NOW(), NOW()),
  ('qnssl.com', 1, '七牛云', NOW(), NOW()),
  ('qnydns.com', 1, '七牛云', NOW(), NOW()),
  ('qnqcdn.net', 1, '七牛云', NOW(), NOW()),
  ('hiecheimaetu.com', 1, '七牛云', NOW(), NOW()),
  ('cy-isp.com', 1, '橙域 CDN', NOW(), NOW()),
  ('71edge.com', 1, '爱奇艺 CDN', NOW(), NOW()),
  ('jcloudcs.com', 1, '京东云 CDN', NOW(), NOW()),
  ('jdcdn.com', 1, '京东云 CDN', NOW(), NOW()),
  ('qianxun.com', 1, '京东云 CDN', NOW(), NOW()),
  ('jcloudlb.com', 1, '京东云 CDN', NOW(), NOW()),
  ('jcloud-cdn.com', 1, '京东云 CDN', NOW(), NOW()),
  ('maoyun.tv', 1, '猫云融合 CDN', NOW(), NOW()),
  ('maoyundns.com', 1, '猫云融合 CDN', NOW(), NOW()),
  ('xgslb.net', 1, 'WebLuker (蓝汛)', NOW(), NOW()),
  ('ucloud.cn', 1, 'UCloud CDN', NOW(), NOW()),
  ('ucloud.com.cn', 1, 'UCloud CDN', NOW(), NOW()),
  ('cdndo.com', 1, 'UCloud CDN', NOW(), NOW()),
  ('zengslb.com', 1, 'Zenlayer CDN', NOW(), NOW()),
  ('zenlogic.net', 1, 'Zenlayer CDN', NOW(), NOW()),
  ('ogslb.com', 1, 'Zenlayer CDN', NOW(), NOW()),
  ('uxengine.net', 1, 'Zenlayer CDN', NOW(), NOW()),
  ('tan14.net', 1, 'TAN14 CDN', NOW(), NOW()),
  ('verycloud.cn', 1, 'VeryCloud 云分发', NOW(), NOW()),
  ('verycdn.net', 1, 'VeryCloud 云分发', NOW(), NOW()),
  ('verygslb.com', 1, 'VeryCloud 云分发', NOW(), NOW()),
  ('xundayun.cn', 1, 'SpeedyCloud CDN', NOW(), NOW()),
  ('xundayun.com', 1, 'SpeedyCloud CDN', NOW(), NOW()),
  ('speedycloud.cc', 1, 'SpeedyCloud CDN', NOW(), NOW()),
  ('mucdn.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('nucdn.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('alphacdn.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('systemcdn.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('edgecastcdn.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('zetacdn.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('comcast.net', 1, 'Verizon CDN (Edgecast)', NOW(), NOW()),
  ('coding.io', 1, 'Coding Pages', NOW(), NOW()),
  ('coding.me', 1, 'Coding Pages', NOW(), NOW()),
  ('gitlab.io', 1, 'GitLab Pages', NOW(), NOW()),
  ('github.io', 1, 'GitHub Pages', NOW(), NOW()),
  ('githubusercontent.com', 1, 'GitHub CDN', NOW(), NOW()),
  ('herokuapp.com', 1, 'Heroku SaaS', NOW(), NOW()),
  ('googleapis.com', 1, 'Google Cloud Storage', NOW(), NOW()),
  ('googlevideo.com', 1, 'YouTube', NOW(), NOW()),
  ('netdna.com', 1, 'Stackpath (原 MaxCDN)', NOW(), NOW()),
  ('netdna-cdn.com', 1, 'Stackpath (原 MaxCDN)', NOW(), NOW()),
  ('netdna-ssl.com', 1, 'Stackpath (原 MaxCDN)', NOW(), NOW()),
  ('cdntip.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('dnsv1.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('dnsv1.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencdns.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('dayugslb.com', 1, '腾讯云大禹 BGP 高防', NOW(), NOW()),
  ('tcdnvod.com', 1, '腾讯云视频 CDN', NOW(), NOW()),
  ('cq-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('cq-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('cq-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('csec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('csec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('cunistatic.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('de-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('de-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('dothework.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('eo-edgefunctions.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('eo-edgefunctions.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('eo-preview.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('eo-shieldspace.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('eo-vpcgw.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('fspstc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('fzec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('fzec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gaapqcloud.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gdzmjs.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('geekpwn.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('govtcloud.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gsadds.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gtm.pub', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gzopen-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gzopen-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gz-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gz-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gz-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gzwxzf-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('gzwxzf-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('haoyunbase.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hfeec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hfeec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hk-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hk-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hotwon.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hotwon.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hotwon.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hotwoncdn.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hr-welink.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hy-clouds.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hzec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('hzec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('igtm.pub', 1, '腾讯云 CDN', NOW(), NOW()),
  ('igtm-meeting-tencent.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('igtm-meeting-tencent.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('in-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('in-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('isd.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jkt-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jkt-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jnec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jnec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jp-tencentclb.cloud', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jp-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jp-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('jrzk.net.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('kbrfyw.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('kgsmpj.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('kr-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('kr-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('lwtsdr.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('manyou.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('max-fame.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('mps.live', 1, '腾讯云 CDN', NOW(), NOW()),
  ('myelasticsearch.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('newglaw.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('nj-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('nj-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('nkfmsp.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('nkwjag.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('nrshog.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('paicang.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('phyto-ceuticals.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('plusrtc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcdnlog.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudcdnsrc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudcdntest.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudcjgj.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudclass.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloud-edumall.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudmarket.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudocdn.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudtcic.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudwaf.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudwzgj.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudzygj.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qeodns.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qeodns.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivertc.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivertc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivertc2.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivertc2.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivewebrtc.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivewebrtc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivewebrtc2.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qlivewebrtc2.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qqmra.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qqmra.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qtmhcj119.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qy-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qy-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qyxa-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qyxa-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('rwph.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sao-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sao-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sao-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sg-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sg-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sg-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('shadc-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('shadc-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sheec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sheec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('shjr-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('shjr-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sh-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sh-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sh-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('shwxzf-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('shwxzf-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sjwec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('sjwec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('srccdn.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('srccdn2.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szjr-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szjr-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szjr-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szjxcft-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szjxcft-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szjxcft-tencentclb.work', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szsycft-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szsycft-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szx-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('szx-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('taihu.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tcloudbh.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tclouddrive.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tcloudlive.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tcloudlive.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tcloudscdn.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tcloudscdn.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tdnsx1.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tenant-zone-dev.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentapigw.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentapigw.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentapigw.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentbyod.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcdb.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcdb.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcdb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentclb.cc', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentclb.cloud', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentclb.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentclb.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentclb.net.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloud-aiot.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudcore.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudcore.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudcr.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudlive.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudlive.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudmarket.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudsso.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentcloudsso.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentdb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentelasticsearch.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentelasticsearch.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentelasticsearch.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentes.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentes.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentes.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenticp.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenticp.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenticp.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentiotcloud.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentiotmedia.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentproxy.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentscf.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentscf.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentscf.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentsmhuc.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentsmhuc.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentsmhuc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenttcr.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenttcr.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenttcr.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencenttione.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentvpc.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentvpc.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tencentvpc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('testjrzk.net.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('testmeet.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('testwaf.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tez-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tez-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('th-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('th-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('timatrix.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('timmerse.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tmcyx.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tourismshow.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tourismuser.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tpe-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tpe-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('trtcrecover.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tsn-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tsn-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tsparkling.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tvodapi.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tvodapibk.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txbyod.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txcloudlive.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txcloudlive.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txelive.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txelive.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txelvb.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txelvb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txlivecdn2.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txmdru.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txtyxg.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txyscdn.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('txyscdn.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('univod.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('use-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('use-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('usw-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('usw-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vigtm-meeting-tencent.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vigtm-meeting-tencent.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodapis.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodapisbk.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vod-bk-qcloud.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodeoapi.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodeoapibk.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodeointernal.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodinternal.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodinternalbk.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('vodxl-qcloud.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('voovmeeting.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('wework-pro.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('wework-studio.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('whec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('whec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('whyrtc.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('winner.hn.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('wxlagame.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('xbec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('xbec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('xiyec-tencentclb.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('xiyec-tencentclb.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('xrgaui.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('yeswan.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('ylgyljr.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('yufuid.com.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('yufuid.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('yufuid.net', 1, '腾讯云 CDN', NOW(), NOW()),
  ('yunjitele.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('zjjj1.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('zxlkbw.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qpic.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('xek.tech', 1, '腾讯云小鹅通 CDN', NOW(), NOW()),
  ('cdn-go.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('spcdntip.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('tcdnlive.com', 1, '腾讯云直播 CDN', NOW(), NOW()),
  ('myqcloud.com', 1, '腾讯云对象存储', NOW(), NOW()),
  ('gaapqcloud.com.cn', 1, '腾讯云全球应用加速', NOW(), NOW()),
  ('tencentcs.com', 1, '腾讯云 API 网关', NOW(), NOW()),
  ('ho-wan.cn', 1, '腾讯云 CDN', NOW(), NOW()),
  ('qcloudcdn.com', 1, '腾讯云 CDN', NOW(), NOW()),
  ('ksyuncdn.com', 1, '金山云 CDN', NOW(), NOW()),
  ('ks-cdn.com', 1, '金山云 CDN', NOW(), NOW()),
  ('kcdnvip.com', 1, '金山云 CDN', NOW(), NOW()),
  ('ksyuncdn-k1.com', 1, '金山云 CDN', NOW(), NOW()),
  ('netlify.app', 1, 'Netlify', NOW(), NOW()),
  ('zeit.co', 1, 'ZEIT Now Smart CDN', NOW(), NOW()),
  ('zeit-cdn.net', 1, 'ZEIT Now Smart CDN', NOW(), NOW()),
  ('b-cdn.net', 1, 'Bunny CDN', NOW(), NOW()),
  ('lsycdn.com', 1, '蓝视云 CDN', NOW(), NOW()),
  ('scsdns.com', 1, '逸云科技云加速 CDN', NOW(), NOW()),
  ('quic.cloud', 1, 'QUIC.Cloud', NOW(), NOW()),
  ('flexbalancer.net', 1, 'FlexBalancer - Smart Traffic Routing', NOW(), NOW()),
  ('gcdn.co', 1, 'G - Core Labs', NOW(), NOW()),
  ('sangfordns.com', 1, '深信服 AD 系列应用交付产品  单边加速解决方案', NOW(), NOW()),
  ('stspg-customer.com', 1, 'StatusPage.io', NOW(), NOW()),
  ('turbobytes.net', 1, 'TurboBytes Multi-CDN', NOW(), NOW()),
  ('turbobytes-cdn.com', 1, 'TurboBytes Multi-CDN', NOW(), NOW()),
  ('att-dsa.net', 1, 'AT&T Content Delivery Network', NOW(), NOW()),
  ('azioncdn.net', 1, '"Azion Tech | Edge Computing PLatform"', NOW(), NOW()),
  ('belugacdn.com', 1, 'BelugaCDN', NOW(), NOW()),
  ('cachefly.net', 1, 'CacheFly CDN', NOW(), NOW()),
  ('inscname.net', 1, 'Instart CDN', NOW(), NOW()),
  ('insnw.net', 1, 'Instart CDN', NOW(), NOW()),
  ('internapcdn.net', 1, 'Internap CDN', NOW(), NOW()),
  ('footprint.net', 1, 'CenturyLink CDN (原 Level 3)', NOW(), NOW()),
  ('llnwi.net', 1, 'Limelight Network', NOW(), NOW()),
  ('llnwd.net', 1, 'Limelight Network', NOW(), NOW()),
  ('unud.net', 1, 'Limelight Network', NOW(), NOW()),
  ('lldns.net', 1, 'Limelight Network', NOW(), NOW()),
  ('stackpathdns.com', 1, 'Stackpath CDN', NOW(), NOW()),
  ('stackpathcdn.com', 1, 'Stackpath CDN', NOW(), NOW()),
  ('mncdn.com', 1, 'Medianova', NOW(), NOW()),
  ('rncdn1.com', 1, 'Relected Networks', NOW(), NOW()),
  ('simplecdn.net', 1, 'Relected Networks', NOW(), NOW()),
  ('swiftserve.com', 1, 'Conversant - SwiftServe CDN', NOW(), NOW()),
  ('bitgravity.com', 1, 'Tata communications CDN', NOW(), NOW()),
  ('zenedge.net', 1, 'Oracle Dyn Web Application Security suite (原 Zenedge CDN)', NOW(), NOW()),
  ('biliapi.com', 1, 'Bilibili 业务 GSLB', NOW(), NOW()),
  ('biliapi.net', 1, 'Bilibili 业务 GSLB', NOW(), NOW()),
  ('bilicdn1.com', 1, 'Bilibili 业务 GSLB', NOW(), NOW()),
  ('hdslb.net', 1, 'Bilibili 负载均衡', NOW(), NOW()),
  ('hdslb.com', 1, 'Bilibili 负载均衡', NOW(), NOW()),
  ('bilivideo.com', 1, '哔哩哔哩视频点播系统', NOW(), NOW()),
  ('bilivideo.cn', 1, '哔哩哔哩视频点播大户PCDN（迅雷网心）', NOW(), NOW()),
  ('szbdyd.com', 1, '哔哩哔哩视频点播散户PCDN（迅雷网心）', NOW(), NOW()),
  ('nodeedge.cn', 1, '长沙市摩根网络科技有限公司PCDN', NOW(), NOW()),
  ('nodecdn.cn', 1, '长沙市摩根网络科技有限公司PCDN', NOW(), NOW()),
  ('mogencloud.com', 1, '长沙市摩根网络科技有限公司PCDN', NOW(), NOW()),
  ('xwaf.cn', 1, '极御云安全(浙江壹云云计算有限公司)', NOW(), NOW()),
  ('shifen.com', 1, '百度旗下业务地域负载均衡系统', NOW(), NOW()),
  ('sinajs.cn', 1, '新浪静态域名', NOW(), NOW()),
  ('tencent-cloud.net', 1, '腾讯旗下业务地域负载均衡系统', NOW(), NOW()),
  ('elemecdn.com', 1, '饿了么静态域名与地域负载均衡', NOW(), NOW()),
  ('sinaedge.com', 1, '新浪科技融合CDN负载均衡', NOW(), NOW()),
  ('sina.com.cn', 1, '新浪科技融合CDN负载均衡', NOW(), NOW()),
  ('sinacdn.com', 1, '新浪云 CDN', NOW(), NOW()),
  ('sinasws.com', 1, '新浪云 CDN', NOW(), NOW()),
  ('saebbs.com', 1, '新浪云 SAE 云引擎', NOW(), NOW()),
  ('websitecname.cn', 1, '美橙互联旗下建站之星', NOW(), NOW()),
  ('cdncenter.cn', 1, '美橙互联CDN', NOW(), NOW()),
  ('vhostgo.com', 1, '西部数码虚拟主机', NOW(), NOW()),
  ('gotoip55.com', 1, '西部数码虚拟主机', NOW(), NOW()),
  ('jsd.cc', 1, '上海云盾YUNDUN', NOW(), NOW()),
  ('powercdn.cn', 1, '动力在线CDN', NOW(), NOW()),
  ('21vokglb.cn', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('21vianet.com.cn', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('21okglb.cn', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('21speedcdn.com', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('21cvcdn.com', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('okcdn.com', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('okglb.com', 1, '世纪互联云快线业务', NOW(), NOW()),
  ('cdnetworks.net', 1, '北京同兴万点网络技术', NOW(), NOW()),
  ('txnetworks.cn', 1, '北京同兴万点网络技术', NOW(), NOW()),
  ('cdnnetworks.com', 1, '北京同兴万点网络技术', NOW(), NOW()),
  ('txcdn.cn', 1, '北京同兴万点网络技术', NOW(), NOW()),
  ('cdnunion.net', 1, '宝腾互联旗下上海万根网络(CDN 联盟)', NOW(), NOW()),
  ('cdnunion.com', 1, '宝腾互联旗下上海万根网络(CDN 联盟)', NOW(), NOW()),
  ('mygslb.com', 1, '宝腾互联旗下上海万根网络(YaoCDN)', NOW(), NOW()),
  ('cdnudns.com', 1, '宝腾互联旗下上海万根网络(YaoCDN)', NOW(), NOW()),
  ('sprycdn.com', 1, '宝腾互联旗下上海万根网络(YaoCDN)', NOW(), NOW()),
  ('chuangcdn.com', 1, '创世云融合 CDN', NOW(), NOW()),
  ('aocde.com', 1, '创世云融合 CDN', NOW(), NOW()),
  ('ctcdn.cn', 1, '中国电信天翼云CDN', NOW(), NOW()),
  ('ctxcdn.cn', 1, '中国电信天翼云CDN', NOW(), NOW()),
  ('ctdns.cn', 1, '中国电信天翼云CDN', NOW(), NOW()),
  ('ctyunapi.cn', 1, '中国电信天翼云 OSS', NOW(), NOW()),
  ('yfcdn.net', 1, '云帆加速CDN', NOW(), NOW()),
  ('mmycdn.cn', 1, '蛮蛮云 CDN(中联利信)', NOW(), NOW()),
  ('chinamaincloud.com', 1, '蛮蛮云 CDN(中联利信)', NOW(), NOW()),
  ('cnispgroup.com', 1, '中联数据(中联利信)', NOW(), NOW()),
  ('cdnle.com', 1, '新乐视云联(原乐视云)CDN', NOW(), NOW()),
  ('gosuncdn.com', 1, '高升控股CDN技术', NOW(), NOW()),
  ('mmtrixopt.com', 1, 'mmTrix性能魔方(高升控股旗下)', NOW(), NOW()),
  ('cloudfence.cn', 1, '蓝盾云CDN', NOW(), NOW()),
  ('ngaagslb.cn', 1, '新流云(新流万联)', NOW(), NOW()),
  ('ngaagslb.net', 1, '新流云(新流万联)', NOW(), NOW()),
  ('clngaa.com', 1, '新流云(新流万联)', NOW(), NOW()),
  ('p2cdn.com', 1, '迅雷星域云PCDN', NOW(), NOW()),
  ('00cdn.com', 1, '迅雷星域云PCDN', NOW(), NOW()),
  ('sankuai.com', 1, '美团云(三快科技)负载均衡', NOW(), NOW()),
  ('lccdn.org', 1, '领智云 CDN(杭州领智云画)', NOW(), NOW()),
  ('nscloudwaf.com', 1, '绿盟云 WAF', NOW(), NOW()),
  ('2cname.com', 1, '网堤安全', NOW(), NOW()),
  ('ucloudgda.com', 1, 'UCloud 罗马 Rome 全球网络加速', NOW(), NOW()),
  ('google.com', 1, 'Google Web 业务', NOW(), NOW()),
  ('1e100.net', 1, 'Google Web 业务', NOW(), NOW()),
  ('ncname.com', 1, 'NodeCache', NOW(), NOW()),
  ('steamstatic.com', 1, 'SteamCDN', NOW(), NOW()),
  ('steamserver.net', 1, 'SteamCDN', NOW(), NOW()),
  ('steamcontent.com', 1, 'SteamCDN', NOW(), NOW()),
  ('valvesoftware.com', 1, 'SteamCDN', NOW(), NOW()),
  ('pphimalayanrt.com', 1, 'SteamCDN(中国大陆)', NOW(), NOW()),
  ('steamchina.com', 1, 'SteamCDN(中国大陆)', NOW(), NOW()),
  ('alipaydns.com', 1, '蚂蚁金服旗下业务地域负载均衡系统', NOW(), NOW()),
  ('alipayobjects.com', 1, '蚂蚁金服旗下业务地域负载均衡系统', NOW(), NOW()),
  ('wscloudcdn.com', 1, '全速云(网宿)CloudEdge 云加速', NOW(), NOW()),
  ('cdngtm.com', 1, '网宿 CDN', NOW(), NOW()),
  ('cdngtm.cn', 1, '网宿 CDN', NOW(), NOW()),
  ('funnull.org', 1, '方能 CDN', NOW(), NOW()),
  ('fnvip100.com', 1, '方能 CDN', NOW(), NOW()),
  ('pcwaf.com', 1, '锐速云 CDN', NOW(), NOW()),
  ('nbwaf.com', 1, '锐速云 CDN', NOW(), NOW()),
  ('yisuddoscdn.com', 1, '亿速云 CDN', NOW(), NOW()),
  ('yunduns.com', 1, '上海云盾', NOW(), NOW()),
  ('hwwsdns.cn', 1, '上海云盾', NOW(), NOW()),
  ('yunduncdn.com', 1, '上海云盾', NOW(), NOW()),
  ('aqyun.com', 1, '知道创宇云安全 CDN', NOW(), NOW()),
  ('jsdun.info', 1, '极速盾', NOW(), NOW()),
  ('vedcdnlb.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('cdnbuild.net', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feishu.net', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('larkoffice.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feishucdn.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('zjurl.cn', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('snssdk.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('pstatp.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feishu-3rd-party-services.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('ttwebview.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('kundou.cn', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('bytetos.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('zijieapi.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feishuimg.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feishuapp.cn', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('getfeishu.cn', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feishupkg.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('feelgood.cn', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('baseopendev.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('douyinvod.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('douyinstatic.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('yhgfb-cn-static.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('douyinpic.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('larksuitecdn.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('ibytedtos.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('douyincdn.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('tiktokcdn.com', 1, '字节跳动旗下火山引擎', NOW(), NOW()),
  ('saaswaf.com', 1, '安恒云 WAF', NOW(), NOW()),
  ('cctvcdn.com', 1, 'CCTVCDN', NOW(), NOW()),
  ('cctvcdn.net', 1, 'CCTVCDN', NOW(), NOW()),
  ('mingfucdn.com', 1, '明赋云', NOW(), NOW()),
  ('cmvideo.cn', 1, '中国移动', NOW(), NOW()),
  ('cmecloud.cn', 1, '中国移动', NOW(), NOW()),
  ('raincdn.cn', 1, '雨云CDN', NOW(), NOW()),
  ('tebi.io', 1, 'tebi 对象储存', NOW(), NOW()),
  ('awswaf.com', 1, 'Amazon云盾', NOW(), NOW()),
  ('awsglobalaccelerator.com', 1, 'Amazon全球加速', NOW(), NOW()),
  ('awsstatic.com', 1, 'AmazonAws', NOW(), NOW()),
  ('aws.dev', 1, 'AmazonAws', NOW(), NOW()),
  ('omtrdc.net', 1, 'AmazonAws', NOW(), NOW()),
  ('a2z.com', 1, 'AmazonAws', NOW(), NOW()),
  ('amazonaws.com.cn', 1, 'Amazon中国区', NOW(), NOW()),
  ('backblazeb2.com', 1, 'BackBlaze对象储存', NOW(), NOW())
;
